### ISSUE TITLE
Doesn't seem to work when nested

### ISSUE THREAD

**Issue by corysimmons** [closingtag/calc-polyfill#11]
Haven't narrowed down this problem but `calc()` doesn't seem to work when it's nested.

![](http://i.imgur.com/Czi3BGw.png)

Not sure if this is related but both calc()'s are using a decimal (99.99%).

**Comment by corysimmons** [comment]
It's not related to decimals.

```html
<section>
  <figure>
    <figure>b</figure>
    <figure>b</figure>
  </figure>
  <figure>a</figure>
</section>
```

```css
section {
  max-width: 980px;
  margin: auto;
  background: #ff0;
  overflow: hidden;
}

figure {
  float: left;
  width: calc(100% / 2);
  background: #f00;
}

figure figure {
  background: #00f;
}
```
