### ISSUE TITLE
Doesn't work with Selectivizr and nth-selectors

### ISSUE THREAD

**Issue by corysimmons** [closingtag/calc-polyfill#23]
```css
.foo {
  background: red; /* works */
  width: calc(100% / 3); /* works */
}

.foo:nth-child(1) {
  background: red; /* works */
  width: calc(100% / 3); /* doesn't work */
}
```

IE8

**Comment by corysimmons** [comment]
This is strange because I remember this working once upon a time.

**Comment by corysimmons** [comment]
Not sure why but it's working with https://github.com/corysimmons/boy

Weird

**Comment by corysimmons** [comment]
Actually I'm not really sure what's going on...

It works on `Browser Mode: IE8` `Document Mode: Standards`, but doesn't work on `Document Mode: IE8 Standards`.

Would you mind fooling with this and seeing if it's broken or what?

**Comment by corysimmons** [comment]
Holy crap, this isn't your fault at all. Selectivizr just doesn't work anymore as far as I can tell. Wtf when did that happen?

```css
.foo:nth-child(1) {
  background: red; /* fails */
}
```

**Comment by corysimmons** [comment]
lol, sorry, it's totally calc polyfill's fault.

I just made a super barebones version and tested selectivizr and it works.

calc polyfill doesn't work with selectivizr though.

**Comment by closingtag** [comment]
@corysimmons This should only work with the version 1.0.3b of selectivizr. See http://selectivizr.com/tests/respond/

**Comment by corysimmons** [comment]
Still doesn't work.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="style.css">
  <script src="bower_components/Selectivizr bower/selectivizr.js"></script> <!-- 1.0.3b -->
  <script src="bower_components/calc-polyfill/dist/calc.min.js"></script> <!-- 0.1.1 (bower ver) -->
</head>
<body>

  <div>hello</div>

  <script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
</body>
</html>
```

``` css
div:nth-child(1n) {
  background: blue;
  width: calc(100% / 3);
}
```

![](https://i.imgur.com/sujLXn5.png)
