### ISSUE TITLE
How hard would it be to make this work with IE Flexbox?

### ISSUE THREAD

**Issue by corysimmons** [closingtag/calc-polyfill#9]
Right now IE doesn't support `calc()` inside of any of their Flexbox rules. (e.g. `flex: 0 0 calc(100% - 30px)` won't work)

Is this something that you could possibly fix?

**Comment by closingtag** [comment]
Right now this polyfill checks if the used browsers supports `calc()`. As IE 10 and higher support `calc()` this script does not polyfill anything in these browsers.

What you can do is to fork is repo and adjust the checking process. Identify IE 10 and higher disregard the check of support for `calc()` and only fix the `calc()` if used within `flex`.

**Comment by corysimmons** [comment]
I don't think I'm smart enough to do that, but thanks for taking the time to answer. I really appreciate all the work you put into this polyfill.

**Comment by mestaritonttu** [comment]
The bug in IE 10 & 11 only affects shorthand rules, though: https://github.com/philipwalton/flexbugs#8-flex-shorthand-doesnt-support-calc

**Comment by corysimmons** [comment]
This is untrue. The bug also affects long hand rules as far as I can tell.

```html
<section>
  <figure>1</figure>
  <figure>2</figure>
</section>
```

```css
* {
  background: rgba(0,0,255,0.1);
}
section {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
figure {
  -webkit-flex-basis: calc(100% / 2);
      -ms-flex-preferred-size: calc(100% / 2);
          flex-basis: calc(100% / 2);
}
```

Renders 2 figures at half the size of the viewport in every browser but IE.
